### ISSUE TITLE
#include <credentials.h>

### ISSUE THREAD

**Issue by kiralikbeyin** [SensorsIot/Internet-of-Things-with-ESP8266#1]
No #include <credentials.h> lib,
...
'ISRbeepTicker' was not declared in this scope
and many other problems.. 

Please can you share credentials.h? Thanks.

**Comment by alexnandes** [comment]
hi @kiralikbeyin ,
i have the same issue, did you solved the problem?
if you solved, can you help me pls?

Thanks

**Comment by kiralikbeyin** [comment]
Hi dont waste your time it is not working

**Comment by alexnandes** [comment]
thank you for your quickly answer, i'm a beginner in esp8266, do you know other project or other code to help me to create a webservices with ESP8266?

**Comment by hjsalom** [comment]
alexnandes & kiralikbeyin:
I had the chance to ask the author directly and found out that the "credentials.h" library does not really exist, it is not a real library to include. That line is just a reminder for him to place in there the SSID and the Password to access the router. So, what you need to do is to remove that line (or put a couple of slashes in front of it) and then insert four instructions: declare the SSID char, the password char, assign the router name to SSID and the access code or password to the password variable. I have experimented other issues or difficulties while compiling with Arduino IDE 1.6.5 but I am confident I am going to find solutions, hopefully.

**Comment by SensorsIot** [comment]
Credentials.h file content:

#define mySSID "xxxx"
#define myPASSWORD "yyyyyyyyyyyyyy"

That's all.
