### ISSUE TITLE
problem coming after uploading program....  rst cause:4,boot mode(1,6)

### ISSUE THREAD

**Issue by sarwadenj** [SensorsIot/Internet-of-Things-with-ESP8266#6]
problem coming after uploading program....

rst cause:4,boot mode(1,6)

GPIO's status after uploading code
CH_PD--VCC
GPIO 15--GND
GPIO 0-Connected to DC MOTOR via N-MOSFET(at uploading connecting to ground)
GPIO 2-Connected to interrupt pin for sensor.....

once MOTOR start rotating after 10sec it throws wdt reset......
previously it is not giving problem with this setup at normal load

after uploading program voltage to ESP12E is getting 3.2v sometime 2.5v and wdt reset fires.........

**Comment by SensorsIot** [comment]
1. The ESP8266 is a 3.3 volt device. If your voltage drops, it can create weired things.
2. Using GPIO0 and GPIO2 is not always a good Idea, They should only be used, if you do not have any others left. If you use tehm, you have to make sure, that the levels for boot are right. If you get the mesage boot mode(1,6) for example, your GPIO0 was low during boot and your ESP waits for flashing. Normal boot should be (3,6)

**Comment by sarwadenj** [comment]
@SensorsIot Thanks, what if i used GPIO 15 instead of GPIO 0 for connecting DC motor, cause no pin left or   or GPIO 15 will also cause same issue.

**Comment by SensorsIot** [comment]
Just try. and pull GPIO0 to Vcc
