### ISSUE TITLE
myPASSWORD capitalization does not match on lines where defined and where used

### ISSUE THREAD

**Issue by dairytech** [SensorsIot/Internet-of-Things-with-ESP8266#7]
In line 38 you define the **myPASSWORD** variable in a comment suggesting the creation of a credentials file.  In line 106 where this variable is used it is spelled **mypassword**.  The compiler does not like this.  You may want to edit the file to make them match.

**Comment by TrullT** [comment]
Yep that's a good idea - no big deal to change once you know, but could be confusing for less experienced programmers.
